### ISSUE TITLE
[BE] 문제 상황이 컨테이너화 되어야 한다

### ISSUE THREAD

**Issue by flydog98** [boostcampwm2023/web01-GitChallenge#7]
- 최초 접속 시 미리 준비되어 있는 컨테이너를 할당받는다.
- 접속 이력(히스토리)이 있는 세션이라면 준비되어 있는 컨테이너에 히스토리를 적용한 뒤 할당한다.
- 컨테이너 생성 시 서버 행동을 로깅한다.

**Comment by LuizyHub** [comment]
[merge close](https://github.com/boostcampwm2023/web01-GitChallenge/pull/82)
